export {AuthorizationPage} from './authorization'
export {RegistrationPage} from './registration'
export {ChatPage} from './chat'
export {ErrorPage} from './error'
export {ProfilePage} from './profile'
